FROM quay.io/keycloak/keycloak:26.3.3

# Admin user
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=adminpassword

# Database (Supabase)
ENV KC_DB=postgres
ENV KC_DB_USERNAME=$KC_DB_USERNAME
ENV KC_DB_PASSWORD=$KC_DB_PASSWORD
ENV KC_DB_URL_HOST=$KC_DB_URL_HOST
ENV KC_DB_URL_PORT=$KC_DB_URL_PORT
ENV KC_DB_URL_DATABASE=$KC_DB_URL_DATABASE

# Render’s runtime port binding
ENV KC_HTTP_PORT=$PORT

# Proxy/hostname config
ENV KC_PROXY=edge
ENV KC_HOSTNAME=$KC_HOSTNAME
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=false
ENV KC_HOSTNAME_DEBUG=$KC_HOSTNAME_DEBUG

EXPOSE 8080

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
